name: publish package

on:
  release:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - id: install dependencies
        run: npm ci
      - id: test
        uses: ./.github/actions/test.yml
      - id: build
        uses: ./.github/actions/build.yml
      - id: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
